### ISSUE TITLE
Using Firefox 36.0.1 and invoking navigator.getVRDevices

### ISSUE THREAD

**Issue by slawrence** [MozVR/MozVR.com-issues#15]
I'm encountering a problem in non-nightly Firefox 36.0.1. First it appears navigator.getVRDevices is actually defined here despite it not being FF Nightly. Secondly, when invoked I get a "NS_ERROR_FAILURE:" error in the console with no hexcode provided.

I wonder if this is local to my system. Is this something that could be caused by having Nightly also installed? I've restarted and still have the problem.

**Comment by vvuk** [comment]
You likely have dom.vr.enabled set to true in your profile.  The APIs will be present in Firefox from version 36 on, but dom.vr.enabled will be set to false by default in anything other than nightly or dev release builds.  If you manually flip it to true though, it will be true in that profile regardless of what browser it's used with.  As far as it failing, that I can't help with, because the APIs are not supported in anything other than nightly/dev, and they internals have changed significantly since then :)
